x = str(input("Unesi bilo koju kombinaciju slova A,B,C: "))
y = list(x)
a = float(y.count("A"))
b = float(y.count("B"))
c = float(y.count("C"))
d = float(a+b+c)
print(round(((a/d)*100),3),"% slova A")
print(round(((b/d)*100),3),"% slova B")
print(round(((c/d)*100),3),"% slova C")
y.sort(reverse=False)
sortirano = ''.join(y)
print("Kad poredamo po abecedi to izgleda ovako: ",sortirano)